obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[-0.2, -0.29], [-0.2, 0.29], [0.56, 0.29], [0.56, -0.29]]
#robot_radius: ir_of_robot
inflation_radius: 0.55
transform_tolerance: 0.5  # TODO: Try to reduce
publish_frequency: 0.25

max_obstacle_height: 2.0

observation_sources: velodyne_scan

velodyne_scan: 
  data_type: LaserScan
  topic: /sensors/laser/scan
  marking: true
  clearing: true
  expected_update_rate: 0.0
velodyne_cloud:
  data_type: PointCloud2
  topic: /sensors/laser/velodyne_points
  marking: true
  clearing: true
  expected_update_rate: 0.5
realsense_sensor:
  data_type: PointCloud2
  topic: /sensors/camera/depth/color/points
  marking: true
  clearing: true
  expected_update_rate: 0.2
