footprint: [[-0.2, -0.29], [-0.2, 0.29], [0.56, 0.29], [0.56, -0.29]]
robot_radius: 0.0
transform_tolerance: 0.5  # TODO: Try to reduce
publish_frequency: 0.25

# Layer configuration
obstacles:
  obstacle_range: 2.5
  raytrace_range: 3.0
  min_obstacle_height: 0.05
  max_obstacle_height: 2.0
  observation_sources: velodyne_obstacles realsense_sensor

  velodyne_obstacles: 
    data_type: PointCloud2
    topic: /sensors/laser/velodyne_obstacles
    marking: true
    clearing: true
    expected_update_rate: 0.0
    obstacle_range: 5
  velodyne_scan: 
    data_type: LaserScan
    topic: /sensors/laser/scan
    marking: true
    clearing: true
    expected_update_rate: 0.0
    obstacle_range: 15
  velodyne_cloud:
    data_type: PointCloud2
    topic: /sensors/laser/velodyne_points
    marking: true
    clearing: true
    expected_update_rate: 0.5
    obstacle_range: 15

  realsense_sensor:
    data_type: PointCloud2
    topic: /sensors/camera/depth/color/points
    marking: true
    clearing: true
    expected_update_rate: 0.2
    min_obstacle_height: 0.02
    obstacle_range: 1.5

  stage_scan: 
    data_type: LaserScan
    topic: /base_scan
    marking: true
    clearing: true
    expected_update_rate: 0.0
    obstacle_range: 15

inflation:
  inflation_radius: 0.55