footprint: [[-0.2, -0.29], [-0.2, 0.29], [0.56, 0.29], [0.56, -0.29]]
robot_radius: 0.0
transform_tolerance: 0.5  # TODO: Try to reduce
publish_frequency: 0.25

# Layer configuration
obstacles_camera:
  obstacle_range: 2.5
  raytrace_range: 3.0
  min_obstacle_height: 0.05
  max_obstacle_height: 2.0
  track_unknown_space: true
  observation_sources: camera_summary

  camera_astra:
    data_type: PointCloud2
    topic: /sensors/camera/depth/points
    marking: true
    clearing: true
    expected_update_rate: 0.2
    min_obstacle_height: 0.02
    obstacle_range: 1.5

  # Low resolution summary of obstacles found by camera processing node.
  camera_summary:
    data_type: PointCloud2
    topic: /sensors/camera/subsampled_points
    marking: true
    clearing: true
    expected_update_rate: 0.2
    min_obstacle_height: 0.02
    obstacle_range: 1.5

obstacles_laser:
  obstacle_range: 2.5
  raytrace_range: 3
  min_obstacle_height: -5.0
  max_obstacle_height: 5.0
  track_unknown_space: true
  observation_sources: velodyne_cloud

  # Voxel parameters
  z_resolution: 0.06
  z_voxels: 16
  publish_voxel_map: true
  treat_z_below_origin_as_free: true
  mark_threshold: 2

  # Sensor configuration
  velodyne_multiscan:
    data_type: LaserScan
    topic: /sensors/laser/multi_scan
    marking: true
    clearing: true
    expected_update_rate: 0.0
    obstacle_range: 10
    raytrace_range: 11
    observation_persistence: 5.0
  #velodyne_scan:
  #  data_type: LaserScan
  #  topic: /sensors/laser/scan
  #  marking: true
  #  clearing: true
  #  expected_update_rate: 0.0
  #  obstacle_range: 10
  velodyne_cloud:
    data_type: PointCloud2
    topic: /sensors/laser/velodyne_points
    marking: true
    clearing: true
    min_obstacle_height: -5.0
    max_obstacle_height: 5.0
    expected_update_rate: 0.5
    obstacle_range: 10
    raytrace_range: 11
  #velodyne_summary:
  #  data_type: PointCloud2
  #  topic: /sensors/laser/subsampled_points
  #  marking: true
  #  clearing: true
  #  expected_update_rate: 0.5
  #  min_obstacle_height: 0.1
  #  obstacle_range: 15

  #stage_scan:
  #  data_type: LaserScan
  #  topic: /base_scan
  #  marking: true
  #  clearing: true
  #  expected_update_rate: 0.0
  #  obstacle_range: 15

inflation:
  inflation_radius: 0.4

social_compliance:
  # Topics
  goal_topic: /move_base_simple/goal
  groups_topic: /spencer/perception/tracked_groups
  people_topic: /spencer/perception/tracked_persons_confirmed_by_HOG_or_upper_body_or_moving
  # Parameters
  behavior_name: rude
  dynamic_scene: true
  human_radius: 0.3
  prediction_horizon: 3
  region_type: anisotropic
  scaled: true
