local_costmap:
  global_frame: odom
  robot_base_frame: base_footprint

  update_frequency: 5.0
  static_map: false
  rolling_window: true
  width: 8.0
  height: 8.0
  resolution: 0.05

  plugins:
    - {name: obstacles_camera,  type: "costmap_2d::ObstacleLayer"}
    - {name: obstacles_laser,   type: "costmap_2d::VoxelLayer"}
    - {name: social_compliance, type: "social_compliance_layer::SocialComplianceLayer"}
    - {name: inflation,         type: "costmap_2d::InflationLayer"}

  # Layer configuration
  #obstacles:
  #inflation:
  #social_compliance: